service: express
provider:
  name: aws
  iam:
    role: arn:aws:iam::986794978521:role/LabRole
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
  apiGateway:
    binaryMediaTypes:
      - '*/*'
functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true